"""add audit tables

Revision ID: eea92202b43b
Revises: c97dcec52018
Create Date: 2026-04-24 14:22:20.368643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eea92202b43b'
down_revision: Union[str, Sequence[str], None] = 'c97dcec52018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_topic_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('wc_category_slug', sa.String(length=300), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('approved', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('wc_catalog_snapshot',
    sa.Column('wp_product_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('species_list', sa.JSON(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('permalink', sa.String(length=500), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('wp_product_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('content_product_mentions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_inventory_id', sa.Integer(), nullable=False),
    sa.Column('wp_product_id', sa.Integer(), nullable=False),
    sa.Column('product_slug', sa.String(length=300), nullable=False),
    sa.Column('product_name', sa.String(length=500), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('first_snippet', sa.Text(), nullable=True),
    sa.Column('match_type', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['content_inventory_id'], ['content_inventory.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_inventory_id', 'wp_product_id', name='uq_content_product_mention')
    )
    op.create_table('content_topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_inventory_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('assigned_by', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['content_inventory_id'], ['content_inventory.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_inventory_id', 'topic_id', name='uq_content_topic')
    )
    op.create_table('decay_findings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_inventory_id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('suggested_action', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detected_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['content_inventory_id'], ['content_inventory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_decay_content_status', 'decay_findings', ['content_inventory_id', 'status'], unique=False)
    op.create_index('ix_decay_rule_status', 'decay_findings', ['rule_name', 'status'], unique=False)
    op.create_table('outbound_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_inventory_id', sa.Integer(), nullable=False),
    sa.Column('href', sa.String(length=2000), nullable=False),
    sa.Column('anchor_text', sa.String(length=500), nullable=True),
    sa.Column('link_type', sa.String(length=30), nullable=False),
    sa.Column('target_content_id', sa.Integer(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['content_inventory_id'], ['content_inventory.id'], ),
    sa.ForeignKeyConstraint(['target_content_id'], ['content_inventory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbound_links_content_inventory_id'), 'outbound_links', ['content_inventory_id'], unique=False)
    op.create_index(op.f('ix_outbound_links_target_content_id'), 'outbound_links', ['target_content_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbound_links_target_content_id'), table_name='outbound_links')
    op.drop_index(op.f('ix_outbound_links_content_inventory_id'), table_name='outbound_links')
    op.drop_table('outbound_links')
    op.drop_index('ix_decay_rule_status', table_name='decay_findings')
    op.drop_index('ix_decay_content_status', table_name='decay_findings')
    op.drop_table('decay_findings')
    op.drop_table('content_topics')
    op.drop_table('content_product_mentions')
    op.drop_table('wc_catalog_snapshot')
    op.drop_table('topics')
    # ### end Alembic commands ###
